name: Create release with wheel

on:
  push:
    tags:
      - "*"

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build package
        run: python -m build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
